version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.27
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: yacJzH11pHq7ttz4kjy1RJw
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql

  caddy:
    image: abiosoft/caddy:0.11.0
    depends_on:
      - "prisma"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - caddy_certs:/root/.caddy

volumes:
  caddy_certs:
  mysql:
